spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
      name: inventory-service
      profile: dit
      label: main

server:
  port: 8081

